default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: payment_development

test:
  <<: *default
  database: payment_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  database: payment_production
  username: payment
  password: <%= ENV["PAYMENT_DATABASE_PASSWORD"] %>
